### ISSUE TITLE
Refactor Django templates to support inheritance

### ISSUE THREAD

**Issue by patgarcia** [sourceoptics/source_optics#169]
[Template inheritance](https://docs.djangoproject.com/en/2.2/ref/templates/language/#template-inheritance) may make it easier to create/maintain templates IMO.

**Comment by mpdehaan** [comment]
template inheritance in Django is confusing to most people. I prefer to use “include”, which works fine.

please do not open tickets for discussions, RFEs, or personal preferences - email is fine if you want
